2016-06-16 22:53:54.974 | +lib/nova_plugins/functions-libvirt:configure_libvirt:134  stop_service libvirt-bin
2016-06-16 22:53:54.977 | +functions-common:stop_service:2300        '[' -x /bin/systemctl ']'
2016-06-16 22:53:54.982 | +functions-common:stop_service:2303        sudo service libvirt-bin stop
2016-06-16 22:53:55.036 | +./stack.sh:exit_trap:494                  echo 'Error on exit'
2016-06-16 22:53:55.000 | stop: Unknown instance: 
2016-06-16 22:53:55.006 | +functions-common:stop_service:1           exit_trap
2016-06-16 22:53:55.036 | Error on exit
2016-06-16 22:53:55.040 | +./stack.sh:exit_trap:495                  generate-subunit 1466117445 192 fail

Solution: 
sudo service libvirt-bin start

:) rsrsrsrs

Abrir chamado no devstack
-----------------------------------------------------------
Instal tacker 

reuirements/upper-constraints.txt (line 154))
2016-06-24 00:20:05.831 | Installing collected packages: tacker
2016-06-24 00:20:05.831 |   Running setup.py develop for tacker
2016-06-24 00:20:07.499 | Successfully installed tacker-0.3.1.dev157
2016-06-24 00:20:07.726 | Installing test-requirements for /opt/stack/tacker/test-requirements.txt
2016-06-24 00:20:08.504 | Ignoring dnspython3: markers u"python_version=='3.4'" don't match your environment
2016-06-24 00:20:08.622 | Ignoring ovs: markers u"python_version=='3.4'" don't match your environment
2016-06-24 00:20:08.792 | Could not satisfy constraints for 'python-tackerclient': installation from path or url cannot be constrained to a version
2016-06-24 00:20:09.010 | Error on exit


/opt/stack/requirements $ rm -rf .venv
/opt/stack/requirements $ virtualenv -p python3 .venv

-----------------------------------------------------------
2016-06-24 13:04:35.082 |   File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
2016-06-24 13:04:35.082 |     raise InternalError(errno, errorvalue)
2016-06-24 13:04:35.082 | sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1833, u"Cannot change column 'id': used in a foreign key constraint 'devices_ibfk_2' of table 'tacker.devices'") [SQL: u'ALTER TABLE vims MODIFY id VARCHAR(36) NULL']
2016-06-24 13:04:35.126 | Error on exit
-----------------------------------------------------------



